name: AgentMark
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.9.25
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==0.20.3
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alfworld==0.4.2
      - altair==6.0.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==4.0.3
      - attrs==25.4.0
      - backoff==2.2.1
      - beautifulsoup4==4.14.2
      - bitsandbytes==0.38.1
      - blinker==1.9.0
      - blis==1.3.3
      - catalogue==2.0.10
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpathlib==0.23.0
      - conda-pack==0.8.1
      - confection==0.1.5
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.13
      - dataclasses-json==0.5.14
      - deepspeed==0.9.2
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - fast-downward-textworld==20.6.4
      - fastapi==0.95.1
      - ffmpy==1.0.0
      - filelock==3.19.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gdown==5.2.0
      - gradio==3.23.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - h11==0.14.0
      - hashids==1.3.1
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jericho==3.3.1
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - langchain==0.0.229
      - langchainplus-sdk==0.0.20
      - linkify-it-py==2.0.3
      - markdown==3.9
      - markdown-it-py==2.2.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.9.4
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mementos==1.3.1
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - murmurhash==1.0.15
      - mypy-extensions==1.1.0
      - narwhals==2.12.0
      - networkx==3.2.1
      - ninja==1.13.0
      - nltk==3.9.2
      - numexpr==2.10.2
      - numpy==1.24.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opacus==1.5.4
      - openai==2.8.1
      - openapi-schema-pydantic==1.2.4
      - opt-einsum==3.4.0
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.3.0
      - pillow==11.3.0
      - preshed==3.0.12
      - prompt-toolkit==3.0.38
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.30.0
      - rich==13.3.5
      - rouge==1.0.1
      - rpds-py==0.27.1
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - semantic-version==2.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - shortuuid==1.0.11
      - six==1.17.0
      - smart-open==7.5.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.44
      - srsly==2.5.2
      - starlette==0.26.1
      - sympy==1.14.0
      - tatsu==5.8.3
      - tenacity==8.5.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - textworld==1.6.2
      - thinc==8.3.9
      - threadpoolctl==3.6.0
      - tiktoken==0.4.0
      - tokenizers==0.13.3
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers>=4.30.0
      - triton==3.4.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - urllib3==2.5.0
      - uvicorn==0.22.0
      - wasabi==1.1.3
      - wcwidth==0.2.14
      - weasel==0.4.3
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - yarl==1.22.0
      - zipp==3.23.0
